server:
  port: 8080

app:
  base-url: http://localhost:8080

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/ecommerce
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: kokonut.hustle@gmail.com
    password: tkvpzmdqhicclgkz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: mySuperSecretKeyThatShouldBeLongEnough
  refresh-secret: mySuperRefreshSecretKeyThatShouldBeLongEnough
  expiration: 3600000
  refresh-expiration: 86400000
